Update dialup profile
Salamek/huawei-lte-api pull request #221
Opened 2024-07-19 11:28 UTC by timvlaer

While working on the api for dialup profiles, I noticed a few things:
* it looks like you can't really control the behaviour of SetDefault when creating a profile. It looks like newly created profiles always become the default, irregardless of the `SetDefault` parameter value. I removed the parameter from the function.
* When creating a profile without dialup_number `DialupNum`, the request failed with error `100001`. It looks to me that this field is not optional... I didn't change this in the code as the example script doesn't have this param. 
* FYI, I couldn't remove the default profile, which has the `ReadOnly` set to `2` (instead of `0` for manually created profiles)

I tested these things against the api of the Huawei E5576-320, so it might be different on other devices.

2024-07-30 22:05 UTC, Salamek commented
@timvlaer ping

2024-07-31 06:29 UTC, timvlaer commented
@Salamek this pr is ready for review. I don’t plan any additions.

2024-07-31 10:32 UTC, Salamek requested changes

2024-07-31 10:32 UTC, Salamek commented
@timvlaer ah sorry my bad, i did not post the review...

2024-07-31 17:37 UTC, timvlaer commented on huawei_lte_api/api/DialUp.py
> +            'SetDefault': 0,
Good point, I’ll revert it

2024-07-31 17:40 UTC, timvlaer commented
My apologies, i am abroad right now without computer so I’ll update this PR as soon as i am back home. That will be the 19th of August.

2024-07-31 18:30 UTC, Salamek commented
@timvlaer that is completely fine ;-) Enjoy your self.

2024-08-19 11:40 UTC, timvlaer commented
Reverted the `is_default` param

2024-08-19 11:56 UTC, Salamek approved these changes

2024-08-19 11:56 UTC, merged